import React, { useEffect } from 'react';
import { ArrowLeft, ArrowDown, Check } from 'lucide-react';
import { FutureSection, CoursesSection, followPointer } from './LandingContent';

export function LandingPage() {
  useEffect(() => {
    const items = Array.from(document.querySelectorAll('.hr-landing section, .hr-landing article, .hr-landing .hr-stat, .hr-landing .hr-learning-card'));
    const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .18 });
    items.forEach(item => { item.classList.add('scroll-reveal'); observer.observe(item); });
    return () => observer.disconnect();
  }, []);
  return <div className="hr-landing">
    <section className="hr-hero hr-shell hr-hero-alive" aria-labelledby="hero-title" onPointerMove={followPointer} onPointerLeave={event => { event.currentTarget.style.setProperty("--rx", "0deg"); event.currentTarget.style.setProperty("--ry", "0deg"); event.currentTarget.style.setProperty("--mx", "30%"); event.currentTarget.style.setProperty("--my", "35%"); }}>
      <div className="hr-hero-copy"><p className="hr-eyebrow"><span />هوش مصنوعی در کار واقعی</p><h1 id="hero-title">ظرفیت بیشتر<br />برای <em>انسان.</em></h1><div className="hr-orbital-visual" aria-hidden="true"><svg viewBox="0 0 500 500"><defs><radialGradient id="orb"><stop stop-color="#4ea6f5"/><stop offset=".7" stop-color="#094D92"/><stop offset="1" stop-color="#062b57"/></radialGradient></defs><g className="orb-rings"><ellipse cx="250" cy="250" rx="190" ry="72" fill="none" stroke="#F1D302" stroke-width="4"/><ellipse cx="250" cy="250" rx="72" ry="190" fill="none" stroke="#F1D302" stroke-width="3" transform="rotate(55 250 250)"/><ellipse cx="250" cy="250" rx="155" ry="155" fill="none" stroke="#70b5f0" stroke-width="2" transform="rotate(-35 250 250)"/></g><circle cx="250" cy="250" r="112" fill="url(#orb)"/><circle cx="178" cy="198" r="13" fill="#F1D302"/><circle cx="337" cy="285" r="11" fill="#F1D302"/><circle cx="300" cy="145" r="8" fill="#fff"/></svg></div><div className="hr-hero-support"><p className="hr-hero-description">با کمک هوش مصنوعی، کار را دوباره ببینیم؛<br className="hr-desktop-break" /> و برای فکر کردن، تصمیم گرفتن و خلق ارزش، جا باز کنیم.</p><p className="hr-hero-detail">هوشران به سازمان‌ها کمک می‌کند استفاده از هوش مصنوعی را به روشی عملی، آگاهانه و تکرارپذیر در کار تیم تبدیل کنند.</p><div className="hr-actions"><a className="hr-button" href="#/assessment">شروع ارزیابی سازمان<ArrowLeft size={19} /></a><a className="hr-text-link" href="#courses">آشنایی با دوره‌ها<ArrowDown size={16} /></a></div></div></div>
      <div className="hr-hero-bottom"><span>از ظرفیت فردی، تا قابلیت سازمانی</span><span dir="ltr">HUMAN + AI</span></div>
    </section>
    <section className="hr-reflection hr-shell" aria-label="هزینه یادگیری هوش مصنوعی"><span className="hr-quote-mark" aria-hidden="true">“</span><blockquote>هزینه‌ی یادگیری هوش مصنوعی، زمان است.<br className="hr-quote-break" /> <strong>هزینه‌ی یادنگرفتنش، جایگاه است.</strong></blockquote><span className="hr-quote-rule" aria-hidden="true" /></section>
    <FutureSection /><CoursesSection />
    <section className="hr-assessment-intro hr-shell" aria-labelledby="assessment-title"><div className="hr-assessment-card"><div className="hr-assessment-copy"><h2 id="assessment-title">از کجا شروع کنیم؟<br /><em>با شناخت وضعیت امروز.</em></h2><p>ارزیابی هوشران کمک می‌کند تصویری از وضعیت فعلی سازمان و فاصله آن با هدفی که در نظر دارید به دست آورید.</p><a className="hr-button" href="#/assessment">ورود به ارزیابی سازمانی<ArrowLeft size={19} /></a></div><div className="hr-assessment-expectations"><div className="hr-assessment-count"><strong>۴۰</strong><span>مؤلفه رفتاری<br />در ۷ بُعد سازمانی</span></div><ul><li><Check size={17} />بررسی وضعیت فعلی و تعیین سطح هدف</li><li><Check size={17} />شناخت نقاط قوت و شکاف‌های اولویت‌دار</li><li><Check size={17} />گزارش و نقشه راه پیشنهادی ۹۰روزه</li></ul><p>نتیجه بر پایه پاسخ‌های شماست و نقطه شروعی برای بررسی دقیق‌تر سازمان محسوب می‌شود.</p></div></div></section>
  </div>;
}